/**
 * Self-score: run crap4ts against its own source and assert the expected
 * threshold breach.
 *
 * This script runs the CLI from source TypeScript via tsx against the
 * coverage generated by `npm run coverage`. It asserts that:
 *
 * 1. The CLI exits with code 2 (CRAP threshold exceeded) — NOT 0 (which
 *    would mean coverage data was not picked up) and NOT 1 (which would
 *    mean invalid input or an unexpected error).
 * 2. The breach is caused by the known-uncovered cli.ts functions
 *    (parseArgs, main) that are excluded from test coverage but included
 *    in source analysis. Specifically:
 *    a. Rows named "parseArgs" and "main" exist in the JSON output.
 *    b. Those rows are unmatched/uncovered (coverageMatched: false or
 *       coverage === 0).
 *    c. Those rows exceed the threshold (crap > threshold).
 *    d. Every other breaching row is also explained (no unexpected-only
 *       breaches).
 *
 * The pure validation logic is in src/self-score-helpers.ts and has unit
 * test coverage via test/self-score.test.ts.
 *
 * The script exits 0 only when the expected breach occurs and is fully
 * explained. It exits non-zero otherwise.
 *
 * Run via: npx tsx scripts/self-score.ts
 *
 * @packageDocumentation
 */

import { execFileSync } from "node:child_process";
import * as path from "node:path";
import * as fs from "node:fs";
import { fileURLToPath } from "node:url";
import {
  validateSelfScoreBreach,
  EXPECTED_BREACH_NAMES,
} from "../src/self-score-helpers.js";
import type { SelfScoreReport } from "../src/self-score-helpers.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const REPO_ROOT = path.resolve(__dirname, "..");
const CLI_SOURCE = path.join(REPO_ROOT, "src/cli.ts");
const COVERAGE_FILE = path.join(REPO_ROOT, "coverage/coverage-final.json");

const THRESHOLD = "30";

interface CliResult {
  stdout: string;
  stderr: string;
  code: number;
}

function runCli(): CliResult {
  if (!fs.existsSync(COVERAGE_FILE)) {
    console.error(
      "Error: coverage/coverage-final.json not found. Run `npm run coverage` first.",
    );
    process.exit(1);
  }
  try {
    const stdout = execFileSync(
      "npx",
      ["tsx", CLI_SOURCE, "src", "--coverage", COVERAGE_FILE, "--threshold", THRESHOLD, "--json"],
      {
        encoding: "utf8",
        timeout: 30000,
        stdio: ["pipe", "pipe", "pipe"],
        cwd: REPO_ROOT,
      },
    );
    return { stdout, stderr: "", code: 0 };
  } catch (e) {
    const err = e as NodeJS.ErrnoException & {
      stdout?: string;
      stderr?: string;
      status?: number;
    };
    return {
      stdout: err.stdout ?? "",
      stderr: err.stderr ?? "",
      code: err.status ?? 1,
    };
  }
}

function assertExpectedBreach(): void {
  const result = runCli();

  if (result.code === 2) {
    let parsed: SelfScoreReport;
    try {
      parsed = JSON.parse(result.stdout) as SelfScoreReport;
    } catch {
      console.error("Error: CLI produced non-JSON output on exit 2:");
      console.error(result.stdout);
      process.exit(1);
    }
    if (!parsed.summary?.breached) {
      console.error(
        "Error: CLI exited 2 but summary.breached is not true. Unexpected state.",
      );
      process.exit(1);
    }

    const thresholdNum = Number(THRESHOLD);
    const validationError = validateSelfScoreBreach(parsed, thresholdNum);
    if (validationError !== null) {
      console.error(`Error: self-score validation failed: ${validationError}`);
      console.error("Breaching rows:");
      const breaches = parsed.rows.filter((r) => r.crap > thresholdNum);
      for (const r of breaches) {
        console.error(
          `  ${r.displayName}: crap=${r.crap.toFixed(1)}, coverage=${r.coverage}, matched=${r.coverageMatched}`,
        );
      }
      process.exit(1);
    }

    console.log(
      `Self-score OK: expected threshold breach confirmed (max CRAP ${parsed.summary.maxCrap?.toFixed(1)} > ${THRESHOLD}).`,
    );
    console.log(
      "The breach is expected: cli.ts functions (parseArgs, main) have high cyclomatic complexity and no direct test coverage (they are exercised via subprocess, which V8 does not attribute to the source file). Coverage fraction semantics: these functions report coverage 0 because no statements within their source range were executed.",
    );
    console.log(
      `Expected breach functions: ${EXPECTED_BREACH_NAMES.join(", ")}.`,
    );
    process.exit(0);
  }

  if (result.code === 0) {
    console.error(
      "Error: self-score CLI exited 0 (no breach). This means coverage data was not picked up or all functions are under threshold. Check that coverage/coverage-final.json is fresh and includes src/ files.",
    );
    console.error("stderr:", result.stderr);
    process.exit(1);
  }

  if (result.code === 1) {
    console.error(
      "Error: self-score CLI exited 1 (invalid input). This is a configuration error, not an expected breach.",
    );
    console.error("stderr:", result.stderr);
    process.exit(1);
  }

  console.error(`Error: self-score CLI exited with unexpected code ${result.code}.`);
  console.error("stderr:", result.stderr);
  process.exit(1);
}

assertExpectedBreach();
